# application-dev.example.yml
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: your-host
    port: your-port
    database: sky_take_out
    username: your-username
    password: your-password

  redis:
    host: your-host
    port: your-port
    password: your-password
    database: 10

ALIOSS_ENDPOINT: oss-cn-beijing.aliyuncs.com
ALIOSS_ACCESS_KEY_ID: your-key
ALIOSS_ACCESS_KEY_SECRET: your-secret
ALIOSS_BUCKET_NAME: your-bucket

JWT_SECRET: your-jwt-secret